### ISSUE TITLE
Issue with rasqual and/or txt2bin.R

### ISSUE THREAD

**Issue by danielleDekker** [dg13/rasqual#1]
Hello,
I'm having trouble running the rasqual program. When i ran the example command shown below with the provided sample data X.bin and Y.bin everything worked correctly. However when I used the X.txt file located in the data directory, re-created the K.txt file from the X.txt using makeOffset.R (then renamed the output to K.txt), and converted these files to .bin with txt2bin.R, and ran the example command again:
> tabix data/chr11.gz 11:2315000-2340000 | bin/rasqual -y data/Y.bin -k data/K.bin -n 24 -j 1 -l 378 -m 62  -s 2316875,2320655,2321750,2321914,2324112 -e 2319151,2320937,2321843,2323290,2324279  -t -f C11orf21 -z

This error is displayed:
> gsl: gamma.c:1180: ERROR: error
> Default GSL error handler invoked.

I also tried running the program with my own dummy data, but this resulted in: 
> 1       SKIPPED         -1      N       N       -1.0    -1.0    -1.0    0.0     0.0     -1.0    -1.0    -1.0    -1.0    -1.0    0       0       -1      -1   -1       0.0     0       -1.0    -1.0

**Comment by natsuhiko** [comment]
Hi,

I'm sorry for the lack of explanation but it is impossible to re-create the offset data "K.txt" from "Y.txt" provided in the test data directory.  The "K.txt" was obtained from the complete expression data matrix (for >50K genes) and I extracted just 2 genes from the complete data.  If you would like to use RASQUAL, firstly you need to create an own read count matrix "Y.txt".  Sorry again for the inconvenience.

Best regards,
Natsuhiko

**Comment by kauralasoo** [comment]
Hi Danielle,

I written some helper R functions to export data in a format suitable for rasqual. You can find them in my fork of the rasqual repository:  https://github.com/kauralasoo/rasqual/tree/master/rasqualTools . The documentation is not complete yet, but maybe you'll find them useful. 

I also have some wrapper scripts that might simplify counting allele-specific expression and running rasqual on multiple genes, but again, they are not completely documented yet:
https://github.com/kauralasoo/rasqual/tree/master/scripts

Hope that helps,
Kaur

**Comment by danielleDekker** [comment]
Thanks for the quick replies, I will give the rasqualTools a try.
