### ISSUE TITLE
The rasqual output

### ISSUE THREAD

**Issue by danielleDekker** [dg13/rasqual#2]
Hello,

My issue is that rasqual doesn't seem to find any ASE sites. I have raw read counts for near 60K genes, from 56 samples. I have used the R script in the rasqual folder to create offset for the gene expression data (without using gc percentage), as well as the txt2bin R script to create the bin files necessary.

I created my own vcf files containing the allele specific reads, of which I've given an example below. The vcf files contain the genotype and allele specific read counts for 56 samples (not the 4 displayed as example). I created a vcf file for each chromosome, resulting in 200K to 800K snps per vcf file.
vcf file example:
> #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  10      11      12      13 
chr18   10659   rs72854246      G       C       100     PASS    RSQ=0.9 GT:AS   0|1:0,0 0|1:0,0 0|1:0,0 0|1:0,0  ....

I have ran rasqual on 100 genes, but each output looked like: 
> ENSG0000000XXX.X_gene  SKIPPED         -1      N       N       -1.0    -1.0    -1.0    0.0     0.0     -1.0    -1.0    -1.0    -1.0    -1.0    0       0       -1      -1      -1      0.0     0       -1.0    -1.0

The command line I used for 1 of these 100 genes looked like this:
> tabix chr_6.vcf.gz -f | bin/rasqual -y gene_expression.bin -k offSet.bin -n 56 -j 10 -l 657704 -m 100 -s 41040684 -e 41067715 -f ENSG00000XXXX.X_gene

eQTL and ASE analysis with other programs have been run on this data, which did provide results.
Could anyone maybe explain why I get no results with rasqual?

Regards,
Danielle

**Comment by natsuhiko** [comment]
Hi Danielle,

It looks the 10th gene (specified by -j 10) is not expressed.  Please check the raw read count data for the gene.

Best regards,
Natsuhiko

**Comment by danielleDekker** [comment]
Hi Natsuhiko,

Each gene I tested is expressed, the 10th gene for example looks like this:

> ENSG00000001167.10_gene 901     1551    1412    1195    1309    1259    1234    1717    1372    1426    1089       1903    1764    1258    1020    917     1289    1151    1421    1306    1461    956     1820    6171233    1542    1409    1125    1013    997     1106    989     902     1498    756     1260    1350    1392       1719    1432    1374    1455    1977    1065    1242    958     1153    1462    1334    1208    8051545    1304    1046    1134    1164

**Comment by natsuhiko** [comment]
Hi Danielle,

What do you get when you run the following command:

tabix chr_6.vcf.gz 6:41040684-41067715 | head -n 10

Best
Natsuhiko

**Comment by danielleDekker** [comment]
This is my result for that area (added in a newline for readability) 

> chr6    41041742        rs4140580       C       T       100     PASS    RSQ=0.9 GT:AS   0|1:2,0 0|0:4,0 0|1:1,1    1|1:0,4 0|1:6,0 0|1:2,1 0|1:0,0 0|1:1,1 1|1:0,11        1|1:0,1 0|1:0,1 0|1:1,3 0|0:2,0 0|0:1,0 0|1:3,4    0|1:0,2 1|1:0,0 0|0:2,0 0|1:1,0 0|1:3,0 0|0:5,0 0|0:0,0 0|1:0,3 0|1:4,1 0|1:0,0 0|1:3,1 1|1:0,2 0|0:2,0    0|0:3,0 0|0:1,0 1|1:0,6 0|0:1,0 0|1:0,2 0|0:8,0 0|0:0,0 0|0:3,0 0|1:2,4 0|1:1,5 0|1:3,2 0|1:2,2 0|0:2,0    1|1:0,0 1|1:0,3 0|1:2,3 0|1:0,0 0|0:2,0 0|0:1,0 0|0:3,0 0|0:3,0 1|1:0,4 0|0:0,0 0|1:0,4 0|0:6,0 0|1:0,0    0|1:0,0 0|0:2,0

> chr6    41041752        rs4140579       G       A       100     PASS    RSQ=0.9 GT:AS   0|1:1,0 0|0:5,0 0|1:1,1    1|1:0,5 0|1:9,0 0|1:3,1 0|1:0,0 0|1:1,2 1|1:0,6 1|1:0,1 0|1:0,1 0|1:2,4 0|0:2,0 0|0:1,0 0|1:2,4 0|1:0,4    1|1:0,3 0|0:2,0 0|1:1,0 0|1:3,0 0|0:4,0 0|0:0,0 0|1:0,3 0|1:4,1 0|1:0,0 0|1:3,1 1|1:0,1 0|0:2,0 0|0:3,0    0|0:1,0 1|1:0,6 0|0:1,0 0|1:0,3 0|0:7,0 0|0:0,0 0|0:3,0 0|1:2,4 0|1:1,6 0|1:3,2 0|1:2,1 0|0:2,0 1|1:0,0    1|1:0,5 0|1:2,3 0|1:0,0 0|0:3,0 0|0:1,0 0|0:3,0 0|0:3,0 1|1:0,4 0|0:0,0 0|1:0,7 0|0:6,0 0|1:0,0 0|1:0,0    0|0:3,0

> chr6    41041829        rs4140578       A       G       100     PASS    RSQ=0.9 GT:AS   0|1:2,0 0|0:7,0 0|1:0,1    1|1:0,5 0|1:5,0 0|1:1,2 0|1:2,0 0|1:0,1 1|1:0,5 1|1:0,2 0|1:0,0 0|1:2,1 0|0:2,0 0|0:6,0 0|1:5,1 0|1:0,3    1|1:0,10        0|0:0,0 0|1:0,0 0|1:2,2 0|0:8,0 0|0:1,0 0|1:0,3 0|1:0,1 0|1:0,0 0|1:1,1 1|1:0,0 0|0:4,0    0|0:0,0 0|0:1,0 1|1:0,1 0|0:0,0 0|1:1,1 0|0:3,0 0|0:0,0 0|0:2,0 0|1:4,2 0|1:0,3 0|1:3,1 0|1:0,4 0|0:5,0    1|1:0,0 1|1:0,4 0|1:0,1 0|1:2,3 0|0:6,0 0|0:6,0 0|0:3,0 0|0:1,0 1|1:0,3 0|0:0,0 0|1:0,13        0|0:1,0    0|1:0,0 0|1:0,2 0|0:2,0
> 
> chr6    41041947        rs62396284      T       A       100     PASS    RSQ=0.9 GT:AS   0|1:5,3 0|0:12,0  0|1:2,0  0|1:2,1 0|0:4,0 0|0:8,0 0|0:4,0 0|0:6,0 0|0:5,0 0|1:2,2 0|1:0,1 0|0:5,0 0|0:3,0 0|0:10,0        0|1:6,2    0|0:4,0 0|0:6,0 0|0:1,0 0|0:7,0 0|0:6,0 0|0:3,0 0|0:3,0 0|0:8,0 0|0:3,0 0|1:3,0 0|0:6,0 1|1:0,2 0|0:10,0   0|0:6,0 0|0:3,0 0|0:3,0 0|0:2,0 0|0:3,0 0|0:4,0 0|0:2,0 0|0:12,0        0|0:3,0 0|0:7,0 0|1:9,5 0|0:10,0   0|0:2,0 0|0:3,0 0|0:9,0 0|0:1,0 0|0:5,0 0|0:4,0 0|0:6,0 0|0:8,0 0|0:8,0 0|0:5,0 0|0:1,0 0|0:15,0  0|0:1,0  0|0:4,0 0|0:4,0 0|0:13,0
> 
> chr6    41042258        rs78616872      G       C       100     PASS    RSQ=0.9 GT:AS   0|0:3,0 0|0:6,0 0|0:1,0    0|0:9,0 0|0:2,0 0|0:8,0 0|0:12,0        0|0:9,0 0|0:6,0 0|0:4,0 0|0:7,0 0|1:3,5 0|0:2,0 0|0:4,0 0|0:5,0    0|0:1,0 0|0:1,1 0|0:7,0 0|0:3,0 0|1:3,3 0|0:3,0 0|0:5,0 0|0:9,0 0|0:4,0 0|0:6,0 0|0:5,0 0|0:8,0 0|0:8,0    0|0:2,0 0|0:10,0        0|0:4,0 0|0:4,0 0|0:4,0 0|0:10,0        0|0:1,0 0|0:5,0 0|0:1,0 0|0:5,0 0|0:13,0   0|0:0,0 0|0:2,0 0|0:5,0 0|1:2,4 0|0:3,0 0|0:5,0 0|0:4,0 0|0:3,0 0|0:8,0 0|0:5,0 0|1:2,1 0|0:3,0 0|0:7,0    0|0:1,0 0|1:11,0        0|0:6,0 0|0:6,0
> 
> chr6    41042590        rs2268188       T       G       100     PASS    RSQ=0.9 GT:AS   0|1:2,0 0|0:2,0 0|1:3,2    1|1:0,1 0|1:0,0 0|1:2,4 0|1:3,1 0|1:2,0 1|1:0,5 1|1:0,3 0|1:0,4 0|1:1,5 0|0:2,0 0|0:8,0 0|1:2,2 0|1:4,0    1|1:0,1 0|0:6,0 0|1:3,0 0|1:4,1 0|0:9,0 0|0:5,0 0|1:3,0 0|1:0,0 0|1:0,1 0|1:4,6 1|1:0,6 0|0:7,0 0|0:10,0   0|0:3,0 1|1:0,3 0|0:1,0 0|1:2,1 0|0:7,0 0|0:2,0 0|0:4,0 0|1:4,4 0|1:4,3 0|1:1,0 0|1:2,3 0|0:3,0 1|1:0,2    1|1:0,9 0|1:3,2 0|1:2,2 0|0:1,0 0|0:0,0 0|0:6,0 0|0:4,2 1|1:0,3 0|0:3,0 0|1:2,7 0|0:7,0 0|1:0,0 0|1:0,1    0|0:3,0
> 
> chr6    41042993        rs2268187       G       A       100     PASS    RSQ=0.9 GT:AS   0|1:1,1 0|0:7,0 0|1:5,6    1|1:0,10        0|1:2,0 0|1:3,3 0|1:4,2 0|1:7,3 1|1:0,6 1|1:0,7 0|1:1,6 0|1:5,2 0|0:7,0 0|0:3,0 0|1:1,6    0|1:2,2 1|1:0,4 0|0:3,0 0|1:0,3 0|1:0,2 0|0:5,0 0|0:3,0 0|1:0,3 0|1:2,0 0|1:4,3 0|1:2,7 1|1:0,15  0|0:8,0  0|0:2,0 0|0:5,0 1|1:0,6 0|0:17,0        0|1:1,2 0|0:8,0 0|0:6,0 0|0:7,0 0|1:7,3 0|1:6,0 0|1:1,2 0|1:1,1    0|0:3,0 1|1:0,5 1|1:0,6 0|1:5,1 0|1:3,2 0|0:9,0 0|0:6,0 0|0:5,0 0|0:5,0 1|1:0,5 0|0:2,0 0|1:2,2 0|0:8,0    0|1:4,6 0|1:1,3 0|0:5,0
> 
> chr6    41043148        rs116149597     T       A       100     PASS    RSQ=0.9 GT:AS   0|0:3,0 0|0:5,0 0|0:9,0    0|0:1,0 0|0:0,0 0|0:2,0 0|0:1,0 0|0:11,0        0|0:3,0 0|0:6,0 0|0:2,0 0|0:3,0 0|0:6,0 0|0:5,0 0|0:2,0    0|0:0,0 0|0:3,0 0|1:2,6 0|0:2,0 0|0:3,0 0|0:3,0 0|0:3,0 0|0:6,0 0|0:4,0 0|0:11,0        0|0:2,0 0|0:5,0    0|0:2,0 0|0:1,0 0|0:1,0 0|0:5,0 0|0:5,0 0|0:0,0 0|0:1,0 0|0:1,0 0|0:3,0 0|0:8,0 0|0:2,0 0|0:4,0 0|0:1,0    0|0:0,0 0|0:3,0 0|0:10,0        0|1:0,0 0|0:0,0 0|0:5,0 0|0:3,0 0|0:0,0 0|0:3,0 0|0:1,0 0|0:1,0 0|0:3,0    0|0:2,0 0|0:0,0 0|0:6,0 0|0:2,0
> 
> chr6    41043203        rs148525630     T       C       100     PASS    RSQ=0.9 GT:AS   0|0:2,0 0|0:3,0 0|0:6,0    0|0:0,0 0|0:1,0 0|1:2,2 0|0:2,0 0|0:7,0 0|0:4,0 0|0:5,0 0|0:2,0 0|0:6,0 0|0:4,0 0|0:2,0 0|0:4,0 0|0:2,0    0|0:2,0 0|0:8,0 0|0:1,0 0|0:4,0 0|0:3,0 0|0:4,0 0|0:7,0 0|0:1,0 0|0:4,0 0|0:1,0 0|0:3,0 0|0:2,0 0|0:0,0    0|0:0,0 0|1:0,2 0|0:3,0 0|0:3,0 0|0:2,0 0|0:3,0 0|0:1,0 0|1:3,3 0|0:1,5 0|0:3,0 0|0:1,0 0|0:0,0 0|1:2,0    0|0:9,0 0|0:0,0 0|0:1,0 0|0:2,0 0|0:3,0 0|0:2,0 0|0:6,0 0|0:1,0 0|0:3,0 0|0:2,0 0|0:2,0 0|0:0,0 0|1:2,0    0|0:1,0
> 
> chr6    41044857        rs116633305     C       T       100     PASS    RSQ=0.9 GT:AS   0|0:2,0 0|0:4,0 0|0:12,0   0|0:3,0 0|0:1,0 0|0:2,0 0|0:3,0 0|0:9,0 0|0:3,0 0|0:2,0 0|0:6,0 0|0:2,0 0|0:2,0 0|0:3,0 0|0:1,0 0|0:1,0    0|0:0,0 0|0:5,0 0|0:2,0 0|0:0,0 0|0:1,0 0|0:2,0 0|0:8,0 0|0:4,0 0|0:5,0 0|0:2,0 0|0:2,0 0|0:4,0 0|0:0,0    0|0:0,0 0|0:0,0 0|0:3,0 0|0:3,0 0|0:6,0 0|0:2,0 0|0:6,0 0|0:6,0 0|0:5,0 0|0:4,0 0|0:7,0 0|0:7,0 0|0:6,0    0|0:5,0 0|0:8,0 0|0:1,0 0|0:2,0 0|0:3,0 0|0:7,0 0|0:2,0 0|0:6,0 0|0:2,0 0|0:2,0 0|0:5,0 0|0:3,0 0|0:2,0    0|0:6,0
>

**Comment by natsuhiko** [comment]
Thanks!

Then, can you try the following three commands?

N=`tabix chr_6.vcf.gz chr6:41040684-41067715 | wc -l | awk '{print $1}'`
echo $N
tabix chr_6.vcf.gz chr6:41040684-41067715 | bin/rasqual \
-y gene_expression.bin -k offSet.bin -n 56 -j 10 -l $N -m $N -f ENSG00000001167 \
-s 41040684,41046768,41048550,41051785,41057318,41057943,41059267,41060651,41062135,41065096 \
-e 41040823,41046903,41048636,41051931,41057449,41058048,41059433,41060824,41062236,41067715 

Best
Natsuhiko

**Comment by danielleDekker** [comment]
Thanks for the quick replies, I really appreciate the help!

There are 50 SNPs around this gene (output of N)

The rasqual output I got from your 3 commands;

> ENSG00000001167 rs6918969       chr6    41049895        T       C       0.330357        1.301196        0.900000   -0.2193022100   3.3883843219    0.531853        0.010000        0.500000        29.150494       7.170419   0       29      5       4       41049895        -419.028315     0       -nan    0.992208

Before I used the amount of total SNPs for the entire chromosome as testing snps( -l option), and provided an estimated amount of feature SNPs (-m 100) , meaning I used the same options for every gene.

Would using tabix to get the real amount of SNPs located on this gene be a good fix for my problem?

**Comment by natsuhiko** [comment]
I hope the following commands work for you:

CHR=chr6
CIS_REG_START=40000000
CIS_REG_END=42000000
GENE_START=41040684
GENE_END=41067715
L=\`tabix chr_6.vcf.gz $CHR:$CIS_REG_START-$CIS_REG_END | wc -l | awk '{print $1}'\`
M=\`tabix chr_6.vcf.gz $CHR:$GENE_START-$GENE_END | wc -l | awk '{print $1}'\`

tabix $CHR:$CIS_REG_START-$CIS_REG_END $CHR.vcf.gz | bin/rasqual ... -l $L -m $M ...

Before using RASQUAL, you need to assemble exon regions for each gene (for -s and -e options).  Otherwise you will get an odd eQTL mapping result by wrongly using AS counts from introns and other genes.

Best
Natsuhiko

**Comment by danielleDekker** [comment]
Thanks, your command worked.
But how did you get the exon regions in the command you gave me to test before?

> tabix chr_6.vcf.gz chr6:41040684-41067715 | bin/rasqual \
-y gene_expression.bin -k offSet.bin -n 56 -j 10 -l $N -m $N -f ENSG00000001167 -t \
-s 41040684,41046768,41048550,41051785,41057318,41057943,41059267,41060651,41062135,41065096 \
-e 41040823,41046903,41048636,41051931,41057449,41058048,41059433,41060824,41062236,41067715

I was also hoping you might clear something up for me, so I might be able to better understand the results;
How is the amount of SNPs located on the gene (the feature 50 SNPs for this gene) used to determine the most likely SNP? I also ran the command with -m 100, which provided the same result.
And when I used this command from before:

> tabix $CHR:$CIS_REG_START-$CIS_REG_END $CHR.vcf.gz | bin/rasqual ... -l $L -m $M ...
> -s 41040684,41046768,41048550,41051785,41057318,41057943,41059267,41060651,41062135,41065096 \
-e 41040823,41046903,41048636,41051931,41057449,41058048,41059433,41060824,41062236,41067715

The resulting SNP had the position: 40213567. Meaning the snp is not in the 50 genes positioned on the gene, and is also positioned far away from the gene's exon positions. Does this mean that rasqual considers all SNPs found within the region given to tabix, and then calculates the most likely SNP ?
I don't see how the amount of feature SNPs and exon positions are contributing to the result here.

**Comment by natsuhiko** [comment]
The exon regions were used in the RASQUAL paper.  The exon regions were simply determined by taking the union of exons in all isoforms of a gene.  You should have had your own gene annotation from which you counted RNA-seq reads.  You should use it to get union of exons for each gene.

As for the "-m" option, it is just to allocate memory on the computer.  So any number larger than the number of feature SNPs is ok to use, otherwise you will encounter memory allocation failure.

RASQUAL tests all SNPs in the cis regulatory region (regardless of the SNP being overlapping with an exon or not).  The feature SNPs (overlapping with any exon) are just used to increase the power and improve fine-mapping of detecting the true causal eQTL SNP (rSNP in our paper).  Those rSNPs may sometimes fall into an exon but usually are found around promoter region of a gene or sometimes >100K far away from TSS.  RASQUAL picks up the most likely rSNP from SNPs tested in the cis regulatory region by means of the likelihood ratio (the bigger the more significant).  If you want to get the test result for all SNPs, you just simply discart "-t" option from the above command.

Best
Natsuhiko

**Comment by danielleDekker** [comment]
Thank you, your explanation is much appreciated !
You've really helped me a lot here  
I will close this issue now

Thanks again,
Danielle
