### ISSUE TITLE
Rasquals Benjamini-Hochberg Q-value output

### ISSUE THREAD

**Issue by danielleDekker** [dg13/rasqual#3]
Hello,

I was wondering why the reported Q-value shows a value that is (always) negative?
To my knowledge a Q-value is an FDR adjusted p-value, and thus could only be between 0 and 1.

While my own results mainly range from a very small number (-0.0000001) to (-9.9999999), the data samples in the data directory resulted in a Q-value of  -13.3941191185.

Would it be possible to get some additional information on how the BH Q-value was calculated ? 

Thanks,

Danielle

**Comment by natsuhiko** [comment]
Hi Danielle,

Sorry for having confused you.

It is log10 Q-value.  You can get the nominal Q-value by 10^(log10 Q).

Best regards,
Natsuhiko

**Comment by danielleDekker** [comment]
Hi Natsuhiko,

Thanks for the quick reply and the clear answer!
