### ISSUE TITLE
error building rasqual

### ISSUE THREAD

**Issue by boxiangliu** [dg13/rasqual#4]
Hello Natsuhiko,

I am having trouble installing rasqual on my local cluster. The error I have is as follows: 

util.c: In function ‘lomax’:
util.c:264:9: error: non-floating-point argument in call to function ‘__builtin_isnan’
         if(x[i]>th && isnan(x[i])==0 && isinf(x[i])==0){
         ^
util.c:264:9: error: non-floating-point argument in call to function ‘__builtin_isinf_sign’
Makefile:23: recipe for target 'util.o' failed
make: *** [util.o] Error 1

I have made sure that CLAPACK and GSL are installed on my system and changed the changed the CFLAGS and LDFLAGS to points to the right directory. 

Any information would be appreciated. 

Bosh

**Comment by natsuhiko** [comment]
Hi Bosh,

Could you let me know the version of gcc and your OS?

Best
Natsuhiko

**Comment by boxiangliu** [comment]
Hi Natsuhiko,

Sorry I missed your comment. 

Here are the information: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609

Our system admin got it to compile after removing -ltmglib from the following line: 

"LDFLAGS := $(LDFLAGS)  -lf2c -lblas -lgslcblas  -llapack -lgsl -lm -lz -ltmglib -lblas -lf2c -lpthread"

In addition, we also added "(double)" to the following line: 

"if(x[i]>th && isnan((double)x[i])==0 && isinf((double)x[i])==0){"

And the program compiled, but we haven't tested whether it would run. 

Is ltmglib necessary for the function of rasqual?

**Comment by natsuhiko** [comment]
Hi Bosh,

Thanks for pointing out.  We don't need libtmglib.  I've updated the Makefile.

Best
Natsuhiko

**Comment by boxiangliu** [comment]
Thanks Natsuhiko!
