### ISSUE TITLE
Wrong number of fSNPs using helper scripts

### ISSUE THREAD

**Issue by liesaweigert** [dg13/rasqual#51]
Hey, I am currently using rasqual with the helper tools from kauralasoo on some ATAC data and a lot of my peaks get skipped with this message: 
The number of fSNPs is greater than that specified by '-m' option.
Aborted...
Since the -m option is calculated by the helper script, I was wondering if there are any common mistakes or special things I should look out for.

**Comment by natsuhiko** [comment]
Hi,

I cannot tell you the trick to modify the rasqualtool, but it looks your input has some issue. Can you paste the actual rasqual command with the feature start position, the feature end position and the number of SNPs within the feature?

Best regards,
Natsuhiko

**Comment by liesaweigert** [comment]
Hey, thank you so much for the answer, here are some examples for the commands. 
tabix VCF_files/GSA_LMU_DEC2020_ATAC_AS.vcf.gz 1:53808893-54209514 | /psycl/g/mpsziller/rasqual/bin/rasqual -y ATAC_out/ATAC.features.final.bin -k ATAC_out/ATAC.offset.final.bin -n 83 -j 3163 -f 1:54008893:54009514 -l 1323 -m 1 -s 54008893 -e 54009514 -z --force --n-threads 16 --w 2e5 -r -x ATAC_out/ATAC.covariates.bin >> output_ATAC/atac_out.final.perm.batch98.txt
tabix VCF_files/GSA_LMU_DEC2020_ATAC_AS.vcf.gz 1:53811620-54212103 | /psycl/g/mpsziller/rasqual/bin/rasqual -y ATAC_out/ATAC.features.final.bin -k ATAC_out/ATAC.offset.final.bin -n 83 -j 3164 -f 1:54011620:54012103 -l 1324 -m 3 -s 54011620 -e 54012103 -z --force --n-threads 16 --w 2e5 -r -x ATAC_out/ATAC.covariates.bin >> output_ATAC/atac_out.final.perm.batch98.txt

**Comment by natsuhiko** [comment]
What is the output for

tabix VCF_files/GSA_LMU_DEC2020_ATAC_AS.vcf.gz 1:54008893-54009514 | wc -l

?

**Comment by liesaweigert** [comment]
The output for the command is 4, and is consistently bigger than the inputs I give them. My problem is that I am computing them using the rasqualTools and I don't know why it's not working correctly or if there is another way to calculate the fSNPs for multiple inputs.

**Comment by natsuhiko** [comment]
Unfortunately I cannot really handle the issue. Please ask Kaur for further help.

Best regards,
Natsuhiko

**Comment by kauralasoo** [comment]
Yes, I was the person who originally wrote rasqualTools, but I haven't touched to code in the past 5 years and I am unable to maintain it. You might be better off preparing the input files for rasqual manually.

**Comment by Zepeng-Mu** [comment]
@liesaweigert Did you update `GSA_LMU_DEC2020_ATAC_AS.vcf.gz` after running rasqualTools? I made this error when I was running rasqual
